---
title: "Pilot analysis"
author: "28819459"
date: "05/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries and working directory
```{r, results='hide', warning=FALSE, message = FALSE}

library(psych)
library(ggridges)
library(kableExtra)
library(mgsub)
library(vroom)
library(stringr)
library(tidyverse)

#Set working directory
setwd("E:/R stuff/Moralisation") #for home PC
#setwd("/home/vanagpau/R/Moralisation") #for laptop

```


## Data import and wrangling
```{r, warning=FALSE, message = FALSE}

setwd("C:/Users/Ben 10/Documents/Paul COG NEURO MSc/Empirical project/MAIN study dummy data")

# read in questionnaire files
df <- do.call(rbind,lapply(list.files(pattern = "*ques*"), read_csv))

# create and tidy dataframe
df <- df %>% select(`Tree Node Key`, `Participant Private ID`, `Question Key`, Response) 
df$`Tree Node Key` <- gsub("questionnaire-", "", df$`Tree Node Key`)
df$Response[df$Response == "1 (not at all)"] <- "1"
df$Response[df$Response == "5 (very much)"] <- "5"

# replace node codes from Gorilla with descriptive names for variables
df$`Tree Node Key` <- mgsub(df$`Tree Node Key`, 
                            c("4bw4","6bjn","a8ji","ay7m","dbk4","dgk1","ekt9","i1ol","kgzr","ooth","ottq","q986","rujl","trbd","u4a6","u6pg","ud7d","udca","y2xo","zbd1","fd9l","v1sb","qtcg","ksqr","webp"), 
                            c("Beh_1","Moremo_3","Hed_1","Diss_4","Debrief","Moremo_1","Morcog_3","Moral_3","Moral_4","Moremo_4","Beh_2","Consent","Diss_3","Hed_4","Moral_1","Diss_1","Hed_3","Morcog_1","Morcog_4","MIS","Moremo_2","Morcog_2","Diss_2","Moral_2","Hed_2"))

# strip out unwanted event code data
df <- df %>% filter(grepl("quantised", `Question Key`)|grepl("obj", `Question Key`))

# tidy up variable names
df$`Question Key` <- gsub("-quantised", "", df$`Question Key`)

# Convert response field to numbers
df$Response <- as.numeric(df$Response)

```

## Data import and wrangling
```{r, warning=FALSE, message = FALSE}

setwd("C:/Users/Ben 10/Documents/Paul COG NEURO MSc/Empirical project/MAIN study dummy data")

# read in questionnaire files
df <- do.call(rbind,lapply(list.files(pattern = "*ques*"), read_csv))

# create and tidy dataframe
df <- df %>% select(`Tree Node Key`, `Participant Private ID`, `Question Key`, Response) 
df$`Tree Node Key` <- gsub("questionnaire-", "", df$`Tree Node Key`)
df$Response <- mgsub(df$Response, c("1 (not at all)", "5 (very much)"), c("1", "5"))


```
