---
title: "Sample Moralisation pilot data"
author: "Paul V"
date: "05/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries and working directory
```{r, echo = FALSE, results='hide', warning=FALSE, message = FALSE}
library(tidyverse)
library(xtable)


## PAUL SETTINGS
setwd("E:/R stuff/Moralisation")

```

## Generate sample data for pilot
```{r}
#create dataframe
# number of participants
n <- 30

# set covariate values of familiarity
f1 <- rnorm(1, 0, 2)
f2 <- rnorm(1, 0, 2)
f3 <- rnorm(1, 0, 2)
f4 <- rnorm(1, 0, 2)

df <- data.frame('PID' = sort(rep(1:n, 4)), 'trial' = rep(c('Cars', 'Meat', 'Plastic', 'e-waste'), n), 'pre_post' = c(rep('pre',n*2), rep('post',n*2)))

df$moral_score <- rnorm(n*4, 0, 2)
df$trial <- factor(df$trial)                                                                                   
df$pre_post <- ordered(df$pre_post, levels = c("pre", "post"))

```
##Descriptive Statistics and Plots
```{r}
df %>% group_by(trial, pre_post) %>% summarise(mean = mean(moral_score))

print(xtable(df %>% group_by(trial, pre_post) %>% summarise(mean = mean(moral_score))), type="html", file="example.html")

df %>% ggplot(aes(x=pre_post, y=moral_score, fill=trial))  + facet_wrap(df$trial) + geom_boxplot() + ggtitle("Comparison of Moralisation score for each issue before and after video stimulus") + ylab("Moral Score") + xlab("")

```

## Example Stats
```{r}

#Simple paired t-test
x <- df %>% filter(trial == 'Cars', pre_post == 'pre') %>% select(moral_score)
y <- df %>% filter(trial == 'Cars', pre_post == 'post') %>% select(moral_score)
t.test(x[,1], y[,1], paired = TRUE, alternative = "two.sided")


```
